[workspace]
changelog_update = false
git_release_enable = false
git_tag_enable = false
git_only = true
semver_check = true
features_always_increment_minor = true

[[package]]
name = "hiro-proxy"
publish = false
